package com.nebuladev.quizgame

class Question
{
     fun question(questionNum : Int): List<String>
    {
        val questionBank = populateQuestions()
        return questionBank[questionNum]
    }

    fun getQuestionLength() : Int
    {
        val questionBank = populateQuestions()
        return questionBank.size - 1
    }


    fun populateQuestions(): List<List<String>>
    {
        var question1 = listOf("What did Roy get arrested for?" , "Drunk Driving" , "Assault" , "Vandalism" , "Theft")
        var question2 = listOf("Who gave up a child?" , "Phyllis" , "Erin" , "Pam" , "Helene")
        var question3 = listOf("What does Pam steal in the first season?" , "Post-It Notes" , "Pencils" , "Tape" , "Paper")
        var question4 = listOf("What's Pam's favorite yogurt flavor?" , "Mixed Berry" , "Cherry" , "Vanilla" , "Blueberry")
        var question5 = listOf("What was Phyllis' nickname in high school?" , "Easy Rider" , "Granny" , "Phil" , "Lazy Lucy")
        var question6 = listOf("Who came up with Suck It?" , "David Wallace" , "Michael" , "Dwight" , "Andy")
        var question7 = listOf("How many brothers does Jim have?" , "Two" , "Three" , "One" , "Four")
        var question8 = listOf("How much did Bob Vance bid on a hug from Phyllis?" , "$1,000" , "$500" , "$5,000" , "$700")
        var question9 = listOf("Where did Pam and Jim's first kiss take place?" , "Chilli's" , "The Office" , "Jim's Party" , "Dwight's Farm")
        var question10 = listOf("What is Erin's real name?" , "Kelly" , "Jan" , "Hannah" , "Julia")
        var question11 = listOf("Who did Kelly get for secret santa?" , "Oscar" , "Pam" , "Ryan" , "Jim")
        var question12 = listOf("Who did Dwight bring to Michael's dinner party?" , "His Babysitter" , "Kelly" , "Angela" , "Pam's Sister")
        var question13 = listOf("What show was Michael on as a kid?" , "Fundle Bundle" , "Scott Bunch" , "Hello Scranton" , "Happy Kids")
        var question14 = listOf("What did Michael buy for the Scott's Tots?" , "Batteries" , "Laptops" , "College" , "Notebooks")
        var question15 = listOf("What does Meredith have a PhD in?" , "School Psychology" , "Teaching" , "Management" , "Child Psychology")
        var question16 = listOf("What is Dwight's favorite movie?" , "The Crow" , "Lord of the Rings" , "Harry Potter" , "Superman")
        var question17 = listOf("What does Michael return with after his trip to Jamaica?" , "Beads in his hair" , "Dreadlocks" , "Goatee" , "Beard")
        var question18 = listOf("How many push-ups does Stanley do to beat Michael?" , "26" , "30" , "40" , "35")
        var question19 = listOf("What is the name of Jim's uprising group?" , "The Fist" , "The Rebellion" , "Paper Pushers" , "The Social Club")
        var question20 = listOf("What is Andy known as after his singing audition goes viral?" , "Baby Wawa" , "Sit There and Cry Guy" , "Audition Guy" , "Cornell Crier")
        var question21 = listOf("What passport other than a US one does Creed have?" , "Swiss" , "German" , "Canadian" , "Australian")
        var question22 = listOf("How many cousins does Dwight have?" , "70" , "10" , "25" , "3")
        var question23 = listOf("How old does Helene turn on her Birthday?" , "58" , "55" , "49" , "59")
        var question24 = listOf("How much does Michael think the first-aid dummy costs?" , "$5,300" , "$35,000" , "$3,500" , "$53,00")
        var question25 = listOf("What is the name of the chair model?" , "Deborah" , "Lynn" , "Carrie" , "Morgan")
        var question26 = listOf( "Which of the was not one of Jim's Halloween costumes?" , "Dwight" , "Three hole Punch Jim" , "Bookface" , "Dave")
        var question27 = listOf("What color shirt does Dwight normally wear?" , "Mustard Yellow" , "Rust Brown" , "Ketchup Red" , "Navy Blue")
        var question28 = listOf("What is Dwight's porcupine's name?","Henrietta","Hilly","Hetty","Henry")
        var question29 = listOf("What is Kelly Kapoor's middle name?" , "Rajnigandha" , "Naya" , "Inaya" , "Diya")
        var question30 = listOf("What is Kelly Hannon's middle name?" , "Erin" , "Samantha" , "Sylvia" , "Pam")
        var question31 = listOf("What does Michael eat instead of ice cream?" , "Mayo and Black Olives" , "Mayo and Cookies" , "Mayo and Pickles" , "Sour cream and Olives")
        var question32 = listOf("What acronym does Creed come up with? " , "BOBODDY" , "NOBODDY" , "DUNDER" , "BOBANY")
        var question33 = listOf("What is Pam's maiden name?" , "Beesly" , "Lader" , "Schaffer" , "Youngs")
        var question34 = listOf("What do Shrutes stand in while getting married?" , "Graves" , "Bath Tub" , "Barn" , "Manure")
        var question35 = listOf("Where does Michael go on a business trip?" , "Winnipeg" , "Montreal" , "Quebec" , "Toronto")
        var question36 = listOf("How many seasons of The Office are there?" , "9" , "8" , "12" , "10")
        var question37 = listOf("How much does Michael's plasma TV cost?" , "$200" , "$100" , "$500" , "$250")
        var question38 = listOf("What is Roy's brother's name?" , "Kenny" , "Nick" , "Troy" , "Chris")
        var question39 = listOf("Who was Pam's replacement when she had the baby?" , "Kathy" , "Katie" , "Karen" , "Katherine")
        var question40 = listOf("What outlet store does Dwight tell Jan to go to?" , "Liz Claiborne" , "Anne Taylor" , "Target" , "Adrianna Papell")
        var question41 = listOf("What does Devon dress up as on Halloween?" , "Homeless man" , "Vampire" , "Mummy" , "Zombie")
        var question42 = listOf("What does Michael put in Toby's desk to frame him?" , "Caprese Salad" , "Spinach" , "Frisee Salad" , "Caesar Salad")
        var question43 = listOf("What clothing does Michael have dry cleaned?" , "Jeans" , "Ties" , "Socks" , "Suit Jacket")
        var question44 = listOf("What is the name of the insurance salesman?" , "Grotti" , "Gotti" , "Gozi" , "Gradle")
        var question45 = listOf("Who tries to kiss Pam at the Diwali celebration?" , "Michael" , "Roy" , "Jim" , "Toby")
        var question46 = listOf("What did Ryan leave in the toaster oven?" , "Cheese Pita" , "Pita Bread" , "Bagel" , "Poptart")
        var question47 = listOf("What is Todd Packer's license plate?" , "WLHUNG" , "PRVRT" , "LOL69" , "BOOBZ")
        var question48 = listOf("What type of farm does Dwight have?" , "Beet" , "Candy" , "Carrot" , "Bear")
        var question49 = listOf("Which of Angela's cats does Dwight kill?" , "Sprinkles" , "Bandit" , "Sparkles" , "Fluffy")
        var question50 = listOf("Who did Michael hit with his car?" , "Meredith" , "Angela" , "Kelly" , "Stanley")
        var question51 = listOf("Who defaced Pam's mural?" , "Frank" , "Brian" , "Nate" , "Clark")
        var question52 = listOf("What is the best pizza place according to the office?" , "Alfredo's Pizza Cafe" , "Pizza by Alfredo" , "Pizza Hut" , "Little Caesars")
        var question53 = listOf("What is Meredith's last name?" , "Palmer" , "Miller" , "Bennet" , "Brooks")
        var question54 = listOf("Who does Phyllis play in the murder mystery game?" , "Beatrix Bourbon" , "Bitsy Buttercup" , "Calista Crawdad" , "Phyllis Phony")
        var question55 = listOf("What movie does Pete know word for word?" , "Die Hard" , "Threat Level Midnight" , "A Quiet Place" , "Million Dollar Baby")
        var question56 = listOf("What does Michael fall into when on a sales call with Jim?" , "Koi Pond" , "Lake" , "Mud Puddle" , "Swimming Pool")
        var question57 = listOf("What was Kevin's high school nickname?" , "Kool-aid-man" , "Lardo" , "Dunder Man" , "Puffy")
        var question58 = listOf("What is Michael's online dating profile name?" , "Little Kid Lover" , "Mike the Magic" , "I Like Kids" , "Kid Hugger")
        var question59 = listOf("What is the IT guy's name?" , "Nick" , "Pete" , "Kent" , "Danny")
        var question60 = listOf("How much weight did the office staff lose?" , "35 lbs" , "30 lbs" , "54 lbs" , "19 lbs")
        var question61 = listOf("Who wins the fun run race?" , "Toby" , "Creed" , "Oscar" , "Dwight")
        var question62 = listOf("Which cat does Angela throw into the ceiling?" , "Bandit" , "Sparkles" , "Sprinkles" , "Princess Lady")
        var question63 = listOf("What was Hidetoshi Hasegawa’s job in Japan?" , "Heart Surgeon" , "Regional Manager" , "Cashier" , "Paper Salesman")
        var question64 = listOf("Who does the senator cheat on Angela with?" , "Oscar" , "Pam" , "Kelly" , "Erin")
        var question65 = listOf("Who breaks the office silent streak?" , "Kevin" , "Michael" , "Toby" , "Andy")
        var question66 = listOf("What kind of car does Dwight own?" , "Trans Am" , "Mustang" , "Jeep" , "Camaro")
        var question67 = listOf("What language does Dwight attempt to teach Erin?" , "Dothraki" , "German" , "Mandarin" , "Klingon")
        var question68 = listOf("Who does Kelly get engaged to?" , "Ravi" , "Ryan" , "Hunter" , "Pete")
        var question69 = listOf("What shape is the Sabre tablet?" , "Triangle" , "Rectangle" , "Square" , "Star")
        var question70 = listOf("What company acquires Dunder Mifflin?" , "Sabre" , "Provean" , "Decovo" , "Zonos")
        var question71 = listOf("Who does Michael not ask to join his new company?" , "Creed" , "Andy" , "Oscar" , "Kelly")
        var question72 = listOf("Where did Pam live when going to art school?" , "New York" , "Los Angeles" , "Philadelphia" , "Washington DC")
        var question73 = listOf("What art school did Pam go to?" , "Pratt" , "Scranton University" , "Glasgow" , "Yale")
        var question74 = listOf("What does Michael think the symbol at Dwight's dojo says?" , "California Roll" , "Sushi Roll" , "Dragon Fire" , "Fish Sandwich")
        var question75 = listOf("What is Meredith allergic to?" , "Dairy" , "Limes" , "Eggs" , "Vodka")
        var question76 = listOf("What is Toby's daughter's name?" , "Sasha" , "CeCe" , "Irina" , "Katherine")
        var question77 = listOf("Who hides in the car while Michael and Dwight prank Utica?" , "Jim" , "Toby" , "Darryl" , "Andy")
        var question78 = listOf("What is the name of the realtor who sells Michael his condo?" , "Carol" , "Holly" , "Carla" , "Camila")
        var question79 = listOf("Whose car is hit by the watermelon dropped off the roof?" , "Stanley" , "Michael" , "Jim" , "Pam")
        var question80 = listOf("How many bedrooms are in Dwight's farmhouse?" , "9" , "14" , "3" , "5")
        var question81 = listOf("Who is the youngest VP in Dunder Mifflin history?" , "Ryan" , "Karen" , "David" , "Jan")
        var question82 = listOf("Who admits to pirating music on their work computer?" , "Kelly" , "Jim" , "Holly" , "Dwight")
        var question83 = listOf("Who gets Jan's old job?" , "Ryan" , "Karen" , "Michael" , "David")
        var question84 = listOf("Which Harry Potter book does Dwight read to Pam and Jim?" , "Deathly Hollows" , "Goblet of Fire" , "Half Blood Prince" , "Order of the Pheonix")
        var question85 = listOf("Who is Jan's assistant?" , "Hunter" , "Michael" , "Rolando" , "Devon")
        var question86 = listOf("Who is Michael Scott's former boss?" , "Ed Truck" , "Dan Gore" , "Kendall" , "Sadiq")
        var question87 = listOf("Who is the HR representative at corporate?" , "Kendall" , "Rolando" , "AJ" , "Madge")
        var question88 = listOf("Who is the security guard at the office?" , "Hank" , "Tony" , "Troy" , "Craig")
        var question89 = listOf("Who is the diversity day speaker?" , "Mr. Brown" , "Mr. Black" , "Billy" , "Martin")
        var question90 = listOf("Who is the convict?" , "Martin" , "Tony" , "Hannah" , "Josh")
        var question91 = listOf("Who is the purse saleswoman?" , "Katy" , "Isabel" , "Jessica" , "Kathy")
        var question92 = listOf("Who is the CEO of Sabre?" , "Jo Bennet" , "Christian Slater" , "Frank" , "Bruce")
        var question93 = listOf("What is Isabel's job?" , "Dental Hygienist" , "Paper Saleswoman" , "Regional Manager" , "Teacher")
        var question94 = listOf("What is the name of Darryl's ex-wife?" , "Justine" , "Gwyneth" , "Jada" , "Stacey")
        var question95 = listOf("Where does Brandon work?" , "Restaurant" , "Warehouse" , "Chilli's" , "Hooters")
        var question96 = listOf("What is the name of Dwight's crime fighting group?" , "Knights of the Night" , "Strangle Stoppers" , "Night Guard" , "Defenders of the Night")
        var question97 = listOf("What was Hannah's job?" , "Accountant" , "Quality Assurance" , "Sales" , "HR")
        var question98 = listOf("Who dates Pam's mom?" , "Michael" , "Dwight" , "Rolf" , "Robert")
        var question99 = listOf("What is the senator's name?" , "Robert" , "Philip" , "Ryan" , "Walter")
        var question100 = listOf("How does Deangelo get hurt?" , "Dunking a Basketball" , "Bow Hunting" , "Playing Soccer" , "Juggling")
        var question101 = listOf("Where did Jim propose to Pam?" , "Gas Station" , "Restaurant" , "Sporting Event" , "Coffee Shop")
        var question102 = listOf("Where did Dwight propose to Angela?" , "Side of the Road" , "The Office" , "Schrute farms" , "Gas Station")
        var question103 = listOf("Who was not a main member of the PPC?" , "Michael" , "Pam" , "Phyllis" , "Angela")
        var question104 = listOf("What is Stanley's daughter's name?" , "Melissa" , "Jasmine" , "Teri" , "Cynthia")
        var question105 = listOf("What cause was the Fun Run raising money for?" , "Rabies" , "Cancer" , "Diabetes" , "Cholera")
        var question106 = listOf("Who does Michael Scott end up marrying?" , "Holly" , "Helene" , "Kathy" , "Katie")
        var question107 = listOf("What is Holly's last name?" , "Flax" , "Flats" , "Scarn" , "Smith")
        var question108 = listOf("What nickname does Andy give to Jim?" , "Big Tuna" , "Small Fry" , "Jimbo" , "Jimothy")
        var question109 = listOf("Who is the best man at Dwight's wedding?" , "Michael" , "Jim" , "Roy" , "Mose")
        var question110 = listOf("What color was prison Mike's bandana?" , "Purple" , "Red" , "Green" , "Blue")
        var question111 = listOf("How much money does Michael give to Oscar's nephew's charity?" , "$25" , "$5" , "$10" , "$12")
        var question112 = listOf("What county is Scranton in?" , "Lackawanna" , "Saskatoon" , "Allegheny" , "Washington")
        var question113 = listOf("Who does Jim take a liking to from the Stamford branch?" , "Karen" , "Hannah" , "Erin" , "Kelly")
        var question114 = listOf("Who plays golden face in \"Threat Level\" midnight?" , "Jim" , "Oscar" , "Toby" , "Michael")
        var question115 = listOf("What kind of shoes does Kevin wear to the wedding?" , "Tissue Boxes" , "Loafers" , "Crocs" , "Slippers")
        var question116 = listOf("What video game does the Stamford branch play?" , "Call of Duty" , "Minecraft" , "Battlefield" , "World of Tanks")
        var question117 = listOf("Who punches a hole in the wall in the office?" , "Andy" , "Michael" , "Dwight" , "Ryan")
        var question118 = listOf("Who shoots a gun in the office?" , "Dwight" , "Jim" , "Pam" , "Roy")
        var question119 = listOf("Who records the printer starting on fire?" , "Darryl" , "Pam" , "Toby" , "Ryan")
        var question120 = listOf("What is Gabe's middle name?" , "Susan" , "Blake" , "Nathan" , "Sammy")
        var question121 = listOf("Who breaks Michael's TV?" , "Jan" , "Todd" , "Jim" , "Angela")
        var question122 = listOf("Who opens their own bar?" , "Kevin" , "Roy" , "Oscar" , "Meredith")
        var question123 = listOf("What is Michael's middle name?" , "Gary" , "Aaron" , "Zeke" , "Ziggy")
        var question124 = listOf("What is Dwight's middle name?" , "Kurt" , "James" , "Jonas" , "Felix")
        var question125 = listOf("What is Pam's middle name?" , "Morgan" , "Erin" , "Sylvia" , "Angela")
        var question126 = listOf("What is Andy's middle name?" , "Baines" , "Walter" , "Charles" , "Aiden")
        var question127 = listOf("What is Ryan's middle name?" , "Bailey" , "Blake" , "Caleb" , "Emerson")
        var question128 = listOf("What is Holly's middle name?" , "Partridge" , "Adeline" , "Noelle" , "Ada")
        var question129 = listOf("What is Deangelo's middle name?" , "Jeremitrius" , "Julian" , "Raine" , "Rocco")
        var question130 = listOf("What is Ryan's son's name?" , "Drake" , "Blake" , "Ricky" , "Cedric")
        var question131 = listOf("Who came up with the \"Big Mac\" idea?" , "Kevin" , "Ryan" , "Karen" , "Jim")
        var question132 = listOf("Who pulls out the cable connection at Gabe's party?" , "Michael" , "Dwight" , "Andy" , "Erin")
        var question133 = listOf("What Dundie does Pam win?" , "Whitest Sneakers" , "Receptionist" , "Best Artist" , "Fine Work")
        var question134 = listOf("What Dundie does Kelly win?" , "Spicy Curry" , "Whitest Sneakers" , "Ethnic" , "Gossip")
        var question135 = listOf("What Dundie does Jim win?" , "Best Dad" , "Tallest" , "Best Dressed" , "Big Tuna")
        var question136 = listOf("What Dundie does Stanley win?" , "Diabetes" , "Crossword" , "Blackest" , "Heart Attack")
        var question137 = listOf("How did Ed Truck die?" , "Decapitation" , "Shot in the Foot" , "Bear Attack" , "Suicide")
        var question138 = listOf("How did Robert Mifflin die?" , "Suicide" , "Decapitation" , "Baler Accident" , "Poisoning")
        var question139 = listOf("Which branch does Jim get transferred to?" , "Stamford" , "Utica" , "Nashua" , "Syracuse")
        var question140 = listOf("Which branch does Holly get transferred to?" , "Nashua" , "New York" , "Stamford" , "Akron")
        var question141 = listOf("Where does Michael move with Holly?" , "Boulder" , "Nashua" , "New York" , "Austin")
        var question142 = listOf("Who gives Dwight his holster as a gift?" , "Uncle Honk" , "Mose" , "Aunt Shirley" , "Jo Bennett")
        var question143 = listOf("What does Sabre sell?" , "Printers" , "Computers" , "Monitors" , "Wallets")
        var question144 = listOf("Who becomes the new CEO of Sabre?" , "Robert California" , "David Wallace" , "Gabe Lewis" , "Michael Scott")
        var question145 = listOf("Who teaches Nellie how to drive?" , "Pam" , "Kelly" , "Andy" , "Ryan")
        var question146 = listOf("Where does Ryan work after being fired?" , "Bowling Alley" , "Laundromat" , "Restaurant" , "Prince Family Paper")
        var question147 = listOf("What is the name of the concierge?" , "Marie" , "Marcus" , "Mary" , "Hollis")
        var question148 = listOf("What dish does Kevin make for the office?" , "Chilli" , "Soup" , "Meatballs" , "Donuts")
        var question149 = listOf("Who hits Meredith with a football?" , "Pam" , "Phyllis" , "Toby" , "Dwight")
        var question150 = listOf("Who beats Michael in the first round of poker?" , "Toby" , "Phyllis" , "Kevin" , "Roy")
        var question151 = listOf("How much does Dwight's fitness orb cost?" , "$25", "$50" , "$90" , "$15")
        var question152 = listOf("What item does Pam buy on the Fun Run?" , "Lamp" , "Pillow" , "Vase" , "Thermos")
        var question153 = listOf("How much does it cost for Jim to dress as Dwight?" , "$11" , "$15" , "$10" , "$20")
        var question154 = listOf("Who wins the Halloween costume contest?" , "Oscar" , "Creed" , "Jim" , "Pam")
        var question155 = listOf("Who is the head of accounting?" , "Angela" , "Oscar" , "Kevin" , "Hannah")
        var question156 = listOf("What is Kevin's made up number?" , "Kelevin" , "Twelve-teen" , "Eighty-Kevin" , "Kevten")
        var question157 = listOf("What is written on the pink hats from Gettysburg?" , "DM does GB" , "Dunders" , "SP at GB" , "DM at GB")
        var question158 = listOf("Who does Dwight dress up as on earth day?" , "Recyclops" , "Recyclebot" , "Trashbot" , "Tree")
        var question159 = listOf("Who does Michael fire on Halloween?" , "Devon" , "Creed" , "Roy" , "Andy")
        var question160 = listOf("What were the olympic medals made from?" , "Yogurt Lids" , "Post-its" , "Soda Cans" , "Cardboard")
        var question161 = listOf("Who does Michael run over with his car?" , "Meredith" , "Toby" , "Stanley" , "Kevin")
        var question162 = listOf("What does Jim suspend in Jello?" , "Stapler" , "Calculator" , "Tape" , "Pencil")
        var question163 = listOf("Who does Dwight kick out of Phyllis's wedding?" , "Uncle Al" , "Elbert" , "Aunt June" , "Aunt Shirley")
        var question164 = listOf("What play is Andy in?" , "Sweeney Todd" , "Wicked" , "Cats" , "Jersey Boys")
        var question165 = listOf("Who replaces Michael?" , "DeAngelo" , "Dwight" , "Jim" , "Gabe")
        var question166 = listOf("Who does Dwight dress as on Christmas?" , "Belsnickle" , "Krampus" , "Santa" , "Das Sanda")
        var question167 = listOf("Who does Michael give his biggest clients?" , "Andy" , "Dwight" , "Jim" , "Stanley")
        var question168 = listOf("What is Angela's favorite Christmas song?" , "Little Drummer Boy" , "Silent Night" , "Hark the Herald Angels" , "Oh Christmas Tree")
        var question169 = listOf("Who announced Pam was pregnant at the wedding?" , "Jim" , "Michael" , "Pam" , "Roy")
        var question170 = listOf("What is Katy's job?" , "Purse Sales" , "Paper Sales" , "Bar Owner" , "Accountant")
        var question171 = listOf("What university did Andy go to?" , "Cornell" , "Dartmouth" , "Princeton" , "Harvard")
        var question172 = listOf("Where does the Booze Cruise take place?" , "Lake Wallenpaupack" , "Lake Scranton" , "Lake Ontario" , "Lake Erie")
        var question173 = listOf("Who shaves their head because of lice?" , "Meredith" , "Kevin" , "Pam" , "Michael")
        var question174 = listOf("What game does Angela tell Pam she plays?" , "Pam-Pong" , "Jim-Jingle" , "Cat-Count" , "Magic-Michael")
        var question175 = listOf("How much did the iPod cost?" , "$400" , "$200" , "$500" , "$450")
        var question176 = listOf("Where do Jim and Pam get married?" , "Niagara" , "Ontario" , "Gas Station" , "The Office")
        var question177 = listOf("Who is the same age as Michael?" , "Phyllis" , "Oscar" , "Creed" , "Kevin")
        var question178 = listOf("What kind of car does Michael hit Meredith with?" , "Sebring" , "PT Cruiser" , "Camry" , "Corolla")
        var question179 = listOf("What club are Pam, Oscar and Toby in?" , "Finer Things" , "Supper" , "Tea-Time" , "Book")
        var question180 = listOf("Who was on the jury for the Scranton Strangler case?" , "Toby" , "Pam" , "Jim" , "Michael")
        var question181 = listOf("What color does Dwight paint Michael's office?" , "Black" , "Brown" , "Red" , "Yellow")
        var question182 = listOf("What food does Michael force Kevin to eat?" , "Broccoli" , "Spinach" , "Nacho Cheese" , "Tuna")
        var question183 = listOf("Who was sent to anger management?" , "Andy" , "Michael" , "Roy" , "Ryan")
        var question184 = listOf("Who was Pam engaged to before Jim?" , "Roy" , "Ryan" , "Oscar" , "Andy")
        var question185 = listOf("Where did Michael and Jan go on vacation?" , "Jamaica" , "Thailand" , "Japan" , "India")
        var question186 = listOf("Where does Ryan claim he went on vacation?" , "Thailand" , "Taiwan" , "Indonesia" , "Australia")
        var question187 = listOf("Who gave the office staff mugs?" , "Kelly" , "Michael" , "Angela" , "Phyllis")
        var question188 = listOf("What was Plop's real name?" , "Pete" , "Clark" , "Edward" , "Patrick")
        var question189 = listOf("Who does Roy marry?" , "Laura" , "Angela" , "Katie" , "Kathy")
        var question190 = listOf("What nickname does Andy give to Oscar?" , "C-SPAN" , "Big Taco" , "Big Tuna" , "Nacho-Countant")
        var question191 = listOf("What did Jan name her baby?" , "Astrid" , "Janet" , "James" , "Michael")
        var question192 = listOf("What is Dunder Mifflin's stock symbol?" , "DMI" , "DMP" , "DMA" , "ADM")
        var question193 = listOf("Whose hair caught on fire on Christmas?" , "Meredith" , "Pam" , "Phyllis" , "Angela")
        var question194 = listOf("Who moves to Costa Rica?" , "Toby" , "Ryan" , "Andy" , "Michael")
        var question195 = listOf("Who breaks their neck?" , "Toby" , "Creed" , "Ryan" , "Roy")
        var question196 = listOf("Who fakes their death?" , "Creed" , "Toby" , "Kevin" , "Darryl")
        var question197 = listOf("Which employee is arrested for fraud?" , "Ryan" , "Dwight" , "Michael" , "Kevin")
        var question198 = listOf("How old was Michael when he learned to talk?" , "5" , "3" , "6" , "9")
        var question199 = listOf("What is the Ben Franklin impersonator's name?" , "Gordon" , "Philip" , "Larry" , "Pete")
        var question200 = listOf("What is Creed's new years resolution?" , "Do a Cartwheel" , "Not Kill Anyone" , "Buy a House" , "Eat Healthier")
        var question201 = listOf("Which restaurant chain was Pam banned from?" , "Chilli's" , "McDonalds" , "Burger King" , "Taco Bell")
        var question202 = listOf("Who is Michael’s favorite actress?" , "Meryl Streep" , "Hillary Swank" , "Sandra Bullock" , "Julia Roberts")
        var question203 = listOf("What is the name of Michael’s book?" , "Somehow I Manage" , "Managing like a Scott" , "Scott's World" , "I manage")
        var question204 = listOf("What name does Michael sign with on diversity day?" , "Daffy Duck" , "Mickey Mouse" , "Chris P. Bacon" , "Sherlock Holmes")
        var question205 = listOf("What movie is the office watching when Jan visits?" , "Varsity Blues" , "Titanic" , "Inception" , "Batman")
        var question206 = listOf("Who celebrates groundhog day privately?" , "Michael" , "Toby" , "Dwight" , "Stanley")
        var question207 = listOf("How many jelly beans does Kevin think are at Pam’s desk?" , "10" , "15" , "102" , "6")
        var question208 = listOf("What does Martin get arrested for?" , "Insider trading" , "Stalking" , "Battery" , "Theft")
        var question209 = listOf("Who did Michael choose to pick out the health care plan?" , "Dwight" , "Jim" , "Jan" , "Karen")
        var question210 = listOf("What is Michael’s favorite type of cake?" , "Mint Chocolate Chip" , "Chocolate" , "Vanilla" , "Strawberry")
        var question211 = listOf("How many times has Meredith been divorced?" , "2" , "6" , "3" , "4")
        var question212 = listOf("What does Dwight think the number one cause of death is?" , "Shotgun Weddings" , "Heart Attack" , "Bear Attacks" , "Landmines")
        var question213 = listOf("Who has two thumbs and hates Todd Packer" , "Jim" , "Pam" , "Stanley" , "Ryan")
        var question214 = listOf("How many apples does Erin eat when bobbing for apples?" , "2" , "1" , "0" , "4")
        var question215 = listOf("What game do Kevin and Oscar play?" , "Hate Ball" , "Flick Ball" , "Paper Ball" , "Dunder Ball")
        var question216 = listOf("Who wins flonkerton in the office olympics?" , "Phyllis" , "Jim" , "Kevin" , "Pam")
        var question217 = listOf("What is Michael’s cast made out of when he burns his foot?" , "Bubble Wrap" , "Cardboard" , "Paper" , "Cardstock")
        var question218 = listOf("Who complain that the men’s bathroom is whites only?" , "Creed" , "Stanley" , "Kevin" , "Toby")
        var question219 = listOf("What is Michael’s favorite pizza joint in New York?" , "Sbarro" , "Pizza Hut" , "Quiznos" , "Joe's Pizza")
        var question220 = listOf("Who complains about Pam planning her wedding at work?" , "Jim" , "Angela" , "Oscar" , "Toby")
        var question221 = listOf("What does Dwight dress up as on the first Halloween?" , "Sith Lord" , "Jim" , "Vampire" , "Bear")
        var question222 = listOf("What room do Pam and Jim stay in at Dwight’s farm?" , "Irrigation" , "America" , "Beets" , "Paper")
        var question223 = listOf("What is the name of Michael’s shoe store idea?" , "Shoe-la-la" , "Scott's Shoes" , "Shoe-Land" , "Shoes-4-Less")
        var question224 = listOf("How much does Dwight sell the princess unicorn dolls for?" , "\$200" , "\$275" , "\$250" , "\$100")
        var question225 = listOf("Which office worker is invited to Dwight’s aunt’s funeral?" , "Oscar" , "Angela" , "Kelly" , "Toby")
        var question226 = listOf("What brand are Pam's white shoes?" , "Keds" , "Nike" , "Adidas" , "Puma")
        var question227 = listOf("What is Jan's ex-husbands last name?" , "Gould" , "Scarn" , "Stills" , "Harris")
        var question228 = listOf("How much does Angela say she weighs?" , "82" , "92" , "102" , "87")

        var question229 = listOf("Who finally met their parents in the last episode?" , "Erin" , "Toby" , "Michael" , "Kevin")
        var question230 = listOf("Andy quits as manager to pursue a career in what?" , "Acting" , "Politics" , "Finance" , "Accounting")
        var question231 = listOf("When returning to the office from the mall who fixes the flat tire?" , "Pam" , "Michael" , "Meredith" , "Jim")
        var question232 = listOf("Who retires and moves to Florida?" , "Stanley" , "Phyllis" , "Michael" , "Pete")
        var question233 = listOf("What kind of building does Stanley want to live in?" , "Lighthouse" , "Book Store" , "Library" , "Mansion")
        var question234 = listOf("Who is hired at the same time as Pete?" , "Clark" , "Ryan" , "James" , "Sarah")
        var question235 = listOf("Which cat is Robert’s favorite?" , "Comstock" , "Sprinkles" , "Princess Lady" , "Bandit")
        var question236 = listOf("What is the name of the spare room Michael plays music in?" , "Cafe Disco" , "Disco Cafe" , "Haunted Disco" , "Dunder Dance-Hall")
        var question237 = listOf("What kind of bear does Jim say is best?" , "Black" , "Brown" , "Polar" , "Grizzly")
        var question238 = listOf("Who has a pet porcupine?" , "Dwight" , "Ryan" , "Daryl" , "Mose")
        var question239 = listOf("Where does Kelly move after getting engaged?" , "Miami" , "Atlanta" , "Boulder" , "Utica")


        var question240 = listOf("Who took up wood carving?" , "Stanley" , "Phyllis" , "Dwight" , "Mose")
        var question241 = listOf("What did Meredith break when she was hit by the car?" , "Pelvis" , "Arm" , "Leg" , "Neck")
        var question242 = listOf("What is Charles Miner’s favorite sport?" , "Soccer" , "Football" , "Rugby" , "Baseball")
        var question243 = listOf("Who has the spare key for the office?" , "Dwight" , "Michael" , "Pam" , "Jim")
        var question244 = listOf("What score did Erin rate Holly out of 40?" , "16" , "24" , "10" , "38")
        var question245 = listOf("How many years were Pam and Roy engaged?" , "3" , "2" , "5" , "6")
        var question246 = listOf("What is Schrute farms biggest attraction?" , "200 Year Old Mattress" , "Bat Weevils" , "Historic Farmhouse" , "Cat Sculpture")
        var question247 = listOf("What is Dwight’s nickname for Angela?" , "Monkey" , "Pumpkin" , "Angel" , "Donut")
        var question248 = listOf("What does Michael add to his diet soda?" , "Sugar" , "Pepper" , "Salt" , "Milk")
        var question249 = listOf("What does Dwight start off with at the yard sale?" , "Pin" , "Candle" , "CD" , "Telescope")
        var question250 = listOf("What is Stanley’s favorite day of the year?" , "Pretzel Day" , "Christmas" , "Groundhog Day" , "Thanksgiving")

        var question251 = listOf("Who is forced by the office staff to get a tattoo?" , "Andy" , "Michael" , "Gabe" , "Oscar")
        var question252 = listOf("Who is the Lizard King?" , "Robert California" , "Oscar" , "Jo" , "Robert Lipton")
        var question253 = listOf("What is Creed’s biggest fear?" , "Snakes" , "Spiders" , "Sharks" , "The Ocean")
        var question254 = listOf("What does Dwight update his emergency contact to?" , "The Hospital" , "Michael" , "Mose" , "Jim")
        var question255 = listOf("What disease did Kevin think he might have?" , "Skin Cancer" , "Diabetes" , "Heart Disease" , "Epilepsy")
        var question256 = listOf("Who proposes at the Diwali celebration?" , "Michael" , "Ryan" , "Roy" , "Jim")
        var question257 = listOf("What weapon does Dwight use to defend Jim?" , "Pepper Spray" , "Nunchucks" , "Throwing Star" , "Sword")
        var question258 = listOf("What is the name of the replacement cat Dwight gives Angela?" , "Garbage" , "Bandit" , "Comstock" , "Sprinkles")
        var question259 = listOf("What is Dwight’s last name in Second Life?" , "Shelford" , "Schrute" , "Sheldon" , "Drute")
        var question260 = listOf("What type of car does Dwight buy from Andy?" , "Xterra" , "Civic" , "Odyssey" , "Sebring")

        var question261 = listOf("Who does Dwight bring to the company picnic?" , "Rolf" , "Mose" , "Aunt Shirley" , "Charles")
        var question262 = listOf("What is the name of Michael’s fake AI?" , "Computron" , "ScarnBot" , "Recyclops" , "DunderBot")
        var question263 = listOf("When Pam is pregnant, who does she eat with?" , "Kevin" , "Oscar" , "Jim" , "Ryan")
        var question264 = listOf("What is the name of the bar owner that Michael flirts with?" , "Donna" , "Helene" , "Deborah" , "Kim")
        var question265 = listOf("What is the name of Michael's nephew who he spanks?" , "Luke" , "Steven" , "Liam" , "Caden")
        var question266 = listOf("How many years of salary did Michael say he spent on Holly’s ring?" , "3" , "1" , "5" , "8")
        var question267 = listOf("What gift does Kevin get himself?" , "Footbath" , "Cook Book" , "Cake" , "iPod")
        var question268 = listOf("What is the scariest animal according to Dwight?" , "Box Jellyfish" , "Shark" , "Killer Whale" , "Bear")
        var question269 = listOf("What does Angela name her baby?" , "Phillip" , "Patrick" , "Cece" , "Luke")
        var question270 = listOf("What does Michael actually order at Hooters?" , "Gourmet Hotdog" , "Chicken Wings" , "Gabagool" , "Spaghetti")

        var question271 = listOf("What do Dwight’s grandparents leave him a large collection of?" , "Armoires" , "Guns" , "Portraits" , "Pillows")
        var question272 = listOf("Who did Kevin get for secret santa?" , "Himself" , "Kelly" , "Dwight" , "Pam")
        var question273 = listOf("What is Pam’s painting of?" , "The Office" , "Niagra" , "Chilli's" , "Scranton")
        var question274 = listOf("What is Dwight’s favorite TV show?" , "Battlestar Galactica" , "Star Trek" , "The Orville" , "Seinfeld")
        var question275 = listOf("How many minutes did Michael work in the office?" , "9,986,000" , "7,784,000," , "4,123,888" , "9,432,423")
        var question276 = listOf("What does Pam study at The Pratt Institute?" , "Graphic Design" , "Photography" , "Painting" , "Drawing")
        var question277 = listOf("What is Jim’s favorite food?" , "Soft-Shell Crab" , "Salmon" , "Steak" , "Lobster")
        var question278 = listOf("What does Oscar give Creed for Secret Santa?" , "Shamrock Keychain" , "Footbath" , "Old Buttonup" , "Deoderant")
        var question279 = listOf("What resort do Michael and Jan go to?" , "Sandals" , "Hedonism" , "Disneyland" , "Montego Bay")
        var question280 = listOf("Who hosts a barbecue that Michael is not invited to?" , "Jim" , "Kevin" , "Roy" , "Stanley")


        var question281 = listOf("Who won the mini-fridge at the casino night?" , "Creed" , "Ryan" , "Phyllis" , "Kevin")
        var question282 = listOf("Which office member is scared of mummies?" , "Kevin" , "Creed" , "Kelly" , "Meredith")
        var question283 = listOf("What is the name of the company that Ryan starts?" , "WUPHF.com" , "RUF.com" , "WUFF.com" , "DOG.com")
        var question284 = listOf("Who plays the president in Michael’s movie?" , "Daryl" , "Mose" , "Troy" , "Ryan")
        var question285 = listOf("Who gets Erin for secret santa?" , "Andy" , "Michael" , "Devon" , "Kevin")
        var question286 = listOf("What kind of candy did Jim and Pam bring back from their honeymoon?" , "Cocoa Leche" , "Skittles" , "Godiva" , "Starbursts")
        var question287 = listOf("How much money did Michael pay to frame Toby for having drugs?" , "\$500" , "\$300" , "\$250" , "\$700")
        var question288 = listOf("Who was Michael Scarn’s trainer in his movie?" , "Cherokee Jack" , "Jack Damien" , "Jericho Williams" , "Travis Barker")
        var question289 = listOf("What did Michael give to Joe as a present?" , "Piece of Coal" , "iPod" , "Baseball Bat" , "Dog Toy")
        var question290 = listOf("What is the name of Stanley's wife?" , "Terry" , "Cynthia" , "Karmen" , "Debbie")
        var question291 = listOf("Who is Gabe mistaken for at Gettysburg?" , "Abraham Lincoln" , "George Washington" , "Andrew Jackson" , "John Adams")













        val questionBank = listOf(question1, question2 , question3, question4, question5 , question6 ,question7 ,question8 ,question9 ,question10,question11,question12,question13,question14,question15,question16,question17,question18,question19,question20,question21,question22,question23 , question24 , question25, question26 , question27, question28 , question29, question30, question31,question32,question33,question34,question35,question36,question37,question38,question39,question40,question41,question42,question43,question44,question45,question46,question47,question48,question49,question50,question51,question52,question53,question54,question55,question56,question57,question58,question59,question60,question61,question62,question63,question64,question65,question66,question67,question68,question69,question70, question71,question72,question73,question74,question75,question76,question77,question78,question79,question80,question81,question82,question83,question84,question85,question86,question87,question88,question89,question90,question91,question92,question93,question94,question95,question96,question97,question98,question99,question100,question101,question102,question103,question104,question105,question106,question107,question108,question109,question110,question111,question112,question113,question114,question115,question116,question117,question118,question119,question120,question121,question122,question123,question124,question125,question126,question127,question128,question129,question130,question131,question132,question133,question134,question135,question136,question137,question138,question139,question140,question141,question142,question143,question144,question145,question146,question147,question148,question149,question150,question151,question152,question153,question154,question155,question156,question157,question158,question159,question160,question161,question162,question163,question164,question165,question166,question167,question168,question169,question170,question171,question172,question173,question174,question175,question176,question177,question178,question179,question180,question181,question182,question183,question184,question185,question186,question187,question188,question189,question190,question191,question192,question193,question194,question195,question196,question197,question198,question199,question200,question201,question202,question203,question204,question205,question206,question207,question208,question209,question210,question211,question212,question213,question214,question215,question216,question217,question218,question219,question220,question221,question222,question223,question224,question225,question226,question227,question228,question229,question230,question231,question232,question233,question234,question235,question236,question237,question238,question239,question240,question241,question242,question243,question244,question245,question246,question247,question248,question249,question250,question251,question252,question253,question254,question255,question256,question257,question258,question259,question260,question261,question262,question263,question264,question265,question266,question267,question268,question269,question270,question271,question272,question273,question274,question275,question276,question277,question278,question279,question280,question281,question282,question283,question284,question285,question286,question287,question288,question289,question290,question291)
        return questionBank;
    }



}